parameters:
    produit_images_directory: '%kernel.project_dir%/public/uploads'

services:
    # Default configuration for services in this file
    _defaults:
        autowire: true      # Automatically inject dependencies
        autoconfigure: true # Automatically register services as commands, event subscribers, etc.

    # Register custom services
    App\Service\MailService:
        arguments:
            $mailer: '@mailer.mailer'
    
    App\EventListener\ProduitStockListener: ~

    # Allow the session service to be injected automatically
    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'

    # Automatically register classes in src/ as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
