parameters:
    produit_images_directory: '%kernel.project_dir%/public/uploads'
    
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\GeminiService:
        arguments:
            $client: '@Symfony\Contracts\HttpClient\HttpClientInterface'
            $apiKey: '%gemini.api_key%'
    # Register custom services
       # Register custom services
    App\Service\MailService:
        arguments:
            $mailer: '@mailer.mailer'

   

    App\EventListener\ProduitStockListener: ~

    # Allow the session service to be injected automatically
    Symfony\Component\HttpFoundation\Session\SessionInterface: '@session'

    # Automatically register classes in src/ as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
